language: c

addons:
  apt:
    packages:
    - python3
    - texlive
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-math-extra
    - latex-xcolor
    - rubber

script:
  - rubber -d notes.tex

before_deploy:
  - python3 scripts/date-tag.py

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "notes.pdf"
  skip_cleanup: true
